site_name: "MeshCentral2 Documentation"
nav:
  - Home: index.md
site_description: "A remote monitoring and management tool"
site_author: " Ylianst"
site_url: "https://git.meshcentral.com/"

# Repository
repo_name: "Ylianst/MeshCentral"
repo_url: "https://github.com/Ylianst/MeshCentral"